// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SlimFaasMcpGateway.Data.CompiledModels
{
    public partial class GatewayDbContextModel
    {
        private GatewayDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("6631587a-9cf0-43f0-bb19-43f3ffb61471"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var auditRecord = AuditRecordEntityType.Create(this);
            var environmentDeploymentMapping = EnvironmentDeploymentMappingEntityType.Create(this);
            var gatewayConfiguration = GatewayConfigurationEntityType.Create(this);
            var tenant = TenantEntityType.Create(this);

            AuditRecordEntityType.CreateAnnotations(auditRecord);
            EnvironmentDeploymentMappingEntityType.CreateAnnotations(environmentDeploymentMapping);
            GatewayConfigurationEntityType.CreateAnnotations(gatewayConfiguration);
            TenantEntityType.CreateAnnotations(tenant);

            AddAnnotation("ProductVersion", "10.0.0");
        }
    }
}
