// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using SlimFaasMcpGateway.Data;
using SlimFaasMcpGateway.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(GatewayDbContext), typeof(GatewayDbContextModel))]
