apiVersion: v1
kind: Namespace
metadata:
  name: slimfaas-demo
  labels:
    name: slimfaas
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: slimfaas
  namespace: slimfaas-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-statefulset-manager
  namespace: slimfaas-demo
rules:
  # On ajoute ici le droit de lister/voir les pods dans ce namespace
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale", "statefulsets/scale"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: slimfaas-deployment-statefulset-manager
  namespace: slimfaas-demo
subjects:
  - kind: ServiceAccount
    name: slimfaas
    namespace: slimfaas-demo
roleRef:
  kind: Role
  name: deployment-statefulset-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: endpoints-viewer
  namespace: slimfaas-demo
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: slimfaas-endpoints-viewer
  namespace: slimfaas-demo
subjects:
  - kind: ServiceAccount
    name: slimfaas
    namespace: slimfaas-demo
roleRef:
  kind: Role
  name: endpoints-viewer
  apiGroup: rbac.authorization.k8s.io
